#!/bin/bash
# Safe rename of 5 Wave 7 directories from EPIC-CCN-XXX to EPIC-W7-XXX
# Generated by identify_wave7_directories_v2.py
set -e

echo "Renaming 5 Wave 7 directories to correct EPIC-W7-XXX format..."

# TryHandleFleetCommand
mv "docs/brain/EPIC-CCN-155" "docs/brain/EPIC-W7-009"
echo "✓ Renamed EPIC-CCN-155 -> EPIC-W7-009"

# ProcessFlattenWorkItem_CancelOrders
mv "docs/brain/EPIC-CCN-98" "docs/brain/EPIC-W7-013"
echo "✓ Renamed EPIC-CCN-98 -> EPIC-W7-013"

# SymmetryGuardReplaceExistingFollowerTarget
mv "docs/brain/EPIC-CCN-128" "docs/brain/EPIC-W7-014"
echo "✓ Renamed EPIC-CCN-128 -> EPIC-W7-014"

# SymmetryGuardTryResolveFollowersForDispatch
mv "docs/brain/EPIC-CCN-129" "docs/brain/EPIC-W7-015"
echo "✓ Renamed EPIC-CCN-129 -> EPIC-W7-015"

# HandleFlatPosition_CleanupActivePositions
mv "docs/brain/EPIC-CCN-023" "docs/brain/EPIC-W7-019"
echo "✓ Renamed EPIC-CCN-023 -> EPIC-W7-019"

echo ""
echo "✅ All 5 directories renamed successfully!"
echo "Wave 7 directories now: 15 total, all with correct EPIC-W7-XXX naming"

# Made with Bob
