#!/usr/bin/env python3
"""
V12 Wave 2 - Quick Launch via SCP + Execute pattern
Uses the RUNNING v12-test-golden-v2 VM to immediately launch Wave 2
No new VM cost, no startup script delay

Usage:
    python scripts/wave2/launch_wave_now.py
"""

import subprocess
import sys
import time
from pathlib import Path
from datetime import datetime, timezone

# ── Config ───────────────────────────────────────────────────────────────────
VM_NAME    = "v12-test-golden-v2"
ZONE       = "us-central1-a"
PROJECT    = "project-14c86305-3cba-493f-a73"
RUN_USER   = "malhitticrypto"
REPO       = f"/home/{RUN_USER}/universal-or-strategy"
MAX_COINS  = "50"
# ─────────────────────────────────────────────────────────────────────────────

EPICS_FILE = Path(__file__).parent / "wave2_epics.txt"


def gcloud(*args, check=True) -> subprocess.CompletedProcess:
    # Use full path to gcloud on Windows
    gcloud_exe = r"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd"
    cmd = [gcloud_exe, *args]
    print(f"[CMD] {' '.join(cmd)}")
    return subprocess.run(cmd, check=check, capture_output=False, text=True, shell=True)


def gcloud_capture(*args) -> str:
    gcloud_exe = r"C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd"
    cmd = [gcloud_exe, *args]
    result = subprocess.run(cmd, check=False, capture_output=True, text=True, shell=True)
    return result.stdout + result.stderr


def load_epics() -> list[tuple[str, str, int]]:
    """Load epics from file. Returns list of (epic_id, method_name, complexity) tuples."""
    epics = []
    for line in EPICS_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("|")
        if len(parts) == 3:
            epic_id, method, cyc = parts
            epics.append((epic_id.strip(), method.strip(), int(cyc.strip())))
    return epics


def build_wave_script(epics: list[tuple[str, str, int]]) -> str:
    """Generate the wave orchestrator script — LF line endings, no $REPO in subshells.

    Key design decisions vs the broken version:
    1. NO set -eu  — dies on first $'\r' if CRLF sneaks in; use explicit || true guards
    2. NO $REPO inside screen's bash -l -c — single-quoted strings don't expand outer vars.
       Use the literal absolute path expanded at Python-generation time instead.
    3. Absolute paths hardcoded by Python — immune to variable-expansion scope issues.
    4. git config --global runs as the RUN_USER via the outer script (already correct user
       because the script is executed with --command as malhitticrypto via gcloud ssh).
    """
    # Expand all paths at Python generation time — never rely on shell $VARS in subshells
    repo_abs = REPO  # /home/malhitticrypto/universal-or-strategy
    logs_abs = f"{repo_abs}/logs"

    lines = [
        "#!/bin/bash",
        "# V12 Wave 2 Orchestrator - Generated by launch_wave_now.py",
        f"# Generated: {datetime.now(timezone.utc).isoformat()}",
        # NO set -eu here — it dies on \r if CRLF ever sneaks through
        "",
        "# Global git identity for Bob checkpointing",
        f'git config --global user.email "malhitticrypto@gmail.com"',
        f'git config --global user.name "malhitticrypto"',
        "",
        f"mkdir -p {logs_abs}",
        "",
        "# Pull latest repo (best-effort)",
        f"cd {repo_abs} && git pull --ff-only origin main || true",
        "",
        "echo '[WAVE2] Launching parallel Bob Shell agents...'",
    ]

    for epic_id, method, cyc in epics:
        session  = f"v12-{epic_id}"
        # Expand log path fully in Python — safe inside single-quoted bash -l -c
        log_path = f"{logs_abs}/{epic_id}.log"
        # Create detailed prompt with method name and complexity
        prompt = f"Run epic-intake for {epic_id}: Extract {method} (complexity {cyc} -> 8)"
        # Use double-quotes for the bash -l -c argument so the shell sees one string.
        # Inner single-quotes are safe inside double-quotes.
        # bob -p prompt uses single-quotes, which are safe inside double-quoted string.
        cmd = (
            f"cd {repo_abs} && "
            f"bob --accept-license --max-coins {MAX_COINS} "
            f"-p '{prompt}' "
            f"> {log_path} 2>&1; "
            f"echo DONE_EXIT=$? >> {log_path}"
        )
        lines.append(f'screen -dmS {session} bash -l -c "{cmd}"')
        lines.append(f"echo '[WAVE2] Launched: {epic_id} ({method}, CYC {cyc})'")
        lines.append("sleep 1")

    lines += [
        "",
        "sleep 2",
        f"echo '[WAVE2] All {len(epics)} agents launched.'",
        "screen -ls || true",
        "",
        f"echo '[WAVE2] Done. Logs: {logs_abs}'",
    ]

    return "\n".join(lines)


def clear_stale_ssh_key():
    """Remove stale Plink key cache entry for the VM's IP."""
    result = gcloud_capture(
        "compute", "instances", "describe", VM_NAME,
        f"--zone={ZONE}", f"--project={PROJECT}",
        "--format=get(networkInterfaces[0].accessConfigs[0].natIP)"
    )
    ip = result.strip().split("\n")[0].strip()
    if not ip:
        print("[WARN] Could not get VM IP for key cache cleanup.")
        return

    print(f"[INFO] VM IP: {ip} — clearing Plink SSH host key cache...")
    import winreg
    try:
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            r"Software\SimonTatham\PuTTY\SshHostKeys",
            0, winreg.KEY_ALL_ACCESS
        )
        vals = []
        try:
            i = 0
            while True:
                name, _, _ = winreg.EnumValue(key, i)
                if ip in name:
                    vals.append(name)
                i += 1
        except OSError:
            pass
        for name in vals:
            winreg.DeleteValue(key, name)
            print(f"[INFO] Removed stale key: {name}")
        winreg.CloseKey(key)
    except Exception as e:
        print(f"[WARN] Could not clear key cache: {e}")


def main():
    epics = load_epics()
    print(f"\n[WAVE2] Preparing to launch {len(epics)} epics on {VM_NAME}")
    epic_summary = ', '.join(f"{eid} ({method}, CYC {cyc})" for eid, method, cyc in epics)
    print(f"[WAVE2] Epics: {epic_summary}\n")

    # Build the orchestrator script locally (no quote escaping!)
    script = build_wave_script(epics)
    script_path = Path("scripts/wave2/_wave2_launch_generated.sh")
    # FIX: open with newline='\n' to force LF-only on Windows.
    # Default write_text() uses os.linesep = '\r\n' on Windows,
    # which causes bash to see $'\r': command not found on every line.
    with open(script_path, 'w', newline='\n', encoding='utf-8') as f:
        f.write(script)
    print(f"[WAVE2] Generated orchestrator: {script_path} (LF line endings)")
    # Verify LF-only
    raw = script_path.read_bytes()
    crlf_count = raw.count(b'\r\n')
    if crlf_count > 0:
        print(f"[ERROR] Script still has {crlf_count} CRLF sequences! Aborting.")
        raise RuntimeError("CRLF detected in generated script")
    print(f"[WAVE2] Line ending check: OK (LF only, {len(script.splitlines())} lines)")

    # Clear stale SSH key cache
    clear_stale_ssh_key()

    # Upload via SCP (no complex quoting — just a file path)
    remote_path = f"/tmp/wave2_launch.sh"
    print(f"\n[WAVE2] Uploading script to {VM_NAME}:{remote_path}...")
    gcloud(
        "compute", "scp",
        str(script_path),
        f"{VM_NAME}:{remote_path}",
        f"--zone={ZONE}",
        f"--project={PROJECT}",
    )
    print("[WAVE2] Upload complete.")

    # Execute via SSH -- simple path, no inline quoting needed
    print(f"\n[WAVE2] Executing on VM...")
    gcloud(
        "compute", "ssh", VM_NAME,
        f"--zone={ZONE}",
        f"--project={PROJECT}",
        f"--command=bash {remote_path}",
    )

    print("\n[WAVE2] [OK] Launch complete!")
    print(f"[WAVE2] Monitor: python scripts/wave2/launch_wave.py --monitor {VM_NAME}")
    print(f"[WAVE2] Or SSH:  gcloud compute ssh {VM_NAME} --zone={ZONE} --command='screen -ls'")


if __name__ == "__main__":
    main()
