#!/usr/bin/env python3
"""
Linear Setup Helper - Get Started with V12 → Linear Integration

This script helps you:
1. Test your Linear API connection
2. Find your Team ID
3. Find your User IDs (for multiple accounts)
4. Generate a .env file for linear_sync.py

Usage:
    python scripts/linear_setup.py
"""

import json
import sys

try:
    import requests
except ImportError:
    print("❌ ERROR: requests library not installed")
    print("📦 Install it with: pip install requests")
    sys.exit(1)


def test_connection(api_key: str) -> bool:
    """Test if API key is valid."""
    query = """
    query {
        viewer {
            id
            name
            email
        }
    }
    """
    
    response = requests.post(
        "https://api.linear.app/graphql",
        headers={
            "Authorization": api_key,
            "Content-Type": "application/json"
        },
        json={"query": query}
    )
    
    if response.status_code == 200:
        data = response.json()
        if "data" in data and "viewer" in data["data"]:
            viewer = data["data"]["viewer"]
            print(f"✅ Connected as: {viewer['name']} ({viewer['email']})")
            print(f"   User ID: {viewer['id']}")
            return True
    
    print(f"❌ Connection failed: {response.text}")
    return False


def get_teams(api_key: str):
    """List all teams in workspace."""
    query = """
    query {
        teams {
            nodes {
                id
                name
                key
            }
        }
    }
    """
    
    response = requests.post(
        "https://api.linear.app/graphql",
        headers={
            "Authorization": api_key,
            "Content-Type": "application/json"
        },
        json={"query": query}
    )
    
    if response.status_code == 200:
        data = response.json()
        teams = data.get("data", {}).get("teams", {}).get("nodes", [])
        
        if teams:
            print("\n📋 Available Teams:")
            for i, team in enumerate(teams, 1):
                print(f"   {i}. {team['name']} (Key: {team['key']})")
                print(f"      Team ID: {team['id']}")
            return teams
        else:
            print("⚠️  No teams found in workspace")
    else:
        print(f"❌ Failed to fetch teams: {response.text}")
    
    return []


def get_users(api_key: str):
    """List all users in workspace."""
    query = """
    query {
        users {
            nodes {
                id
                name
                email
                active
            }
        }
    }
    """
    
    response = requests.post(
        "https://api.linear.app/graphql",
        headers={
            "Authorization": api_key,
            "Content-Type": "application/json"
        },
        json={"query": query}
    )
    
    if response.status_code == 200:
        data = response.json()
        users = data.get("data", {}).get("users", {}).get("nodes", [])
        
        if users:
            print("\n👥 Available Users:")
            for i, user in enumerate(users, 1):
                status = "✓ Active" if user.get("active") else "✗ Inactive"
                print(f"   {i}. {user['name']} ({user['email']}) - {status}")
                print(f"      User ID: {user['id']}")
            return users
        else:
            print("⚠️  No users found in workspace")
    else:
        print(f"❌ Failed to fetch users: {response.text}")
    
    return []


def generate_env_file(api_key: str, team_id: str, user_ids: list):
    """Generate .env file for linear_sync.py."""
    env_content = f"""# Linear Integration Configuration
# Generated by linear_setup.py on {__import__('datetime').datetime.now().isoformat()}

# Your Linear API Key (keep this secret!)
LINEAR_API_KEY={api_key}

# Team ID for V12 project
LINEAR_TEAM_ID={team_id}

# User IDs to assign tasks to (comma-separated for multiple accounts)
LINEAR_ASSIGNEE_IDS={','.join(user_ids)}

# Optional: Workspace name
LINEAR_WORKSPACE_NAME="V12 Development"
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ Created .env file")
    print("⚠️  IMPORTANT: .env contains your API key - never commit it to git!")


def main():
    print("=" * 60)
    print("🚀 Linear Setup Helper - V12 Integration")
    print("=" * 60)
    
    # Step 1: Get API Key
    print("\n📝 Step 1: Get your Linear API Key")
    print("   1. Go to: https://linear.app/settings/api")
    print("   2. Click 'Create new key'")
    print("   3. Give it a name (e.g., 'V12 Sync')")
    print("   4. Copy the key (starts with 'lin_api_')")
    print()
    
    api_key = input("Paste your Linear API key here: ").strip()
    
    if not api_key:
        print("❌ No API key provided. Exiting.")
        sys.exit(1)
    
    # Step 2: Test Connection
    print("\n🔌 Step 2: Testing connection...")
    if not test_connection(api_key):
        print("❌ Connection test failed. Check your API key.")
        sys.exit(1)
    
    # Step 3: Get Teams
    print("\n📋 Step 3: Finding your teams...")
    teams = get_teams(api_key)
    
    if not teams:
        print("❌ No teams found. Create a team in Linear first.")
        sys.exit(1)
    
    # Select team
    if len(teams) == 1:
        selected_team = teams[0]
        print(f"\n✅ Using team: {selected_team['name']}")
    else:
        team_choice = input(f"\nSelect team (1-{len(teams)}): ").strip()
        try:
            selected_team = teams[int(team_choice) - 1]
        except (ValueError, IndexError):
            print("❌ Invalid selection. Exiting.")
            sys.exit(1)
    
    # Step 4: Get Users
    print("\n👥 Step 4: Finding users in workspace...")
    users = get_users(api_key)
    
    if not users:
        print("⚠️  No users found, but continuing...")
        selected_users = []
    else:
        print("\nSelect users to assign tasks to (comma-separated, e.g., 1,3):")
        print("(Press Enter to skip user assignment)")
        user_choice = input("Your choice: ").strip()
        
        selected_users = []
        if user_choice:
            try:
                indices = [int(x.strip()) - 1 for x in user_choice.split(",")]
                selected_users = [users[i]["id"] for i in indices if 0 <= i < len(users)]
            except (ValueError, IndexError):
                print("⚠️  Invalid selection, skipping user assignment")
    
    # Step 5: Generate .env
    print("\n💾 Step 5: Generating configuration...")
    generate_env_file(api_key, selected_team["id"], selected_users)
    
    # Step 6: Next Steps
    print("\n" + "=" * 60)
    print("✅ Setup Complete!")
    print("=" * 60)
    print("\n📚 Next Steps:")
    print("   1. Review the generated .env file")
    print("   2. Run the sync script:")
    print("      python scripts/linear_sync.py")
    print()
    print("   3. Or test with dry-run first:")
    print("      python scripts/linear_sync.py --dry-run")
    print()
    print("📖 Full documentation: docs/LINEAR_INTEGRATION.md")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        sys.exit(1)

# Made with Bob
