#!/bin/bash
# V12 Wave 2 Orchestrator - Generated by launch_wave_now.py
# Generated: 2026-06-12T09:50:12.801809+00:00

# Global git identity for Bob checkpointing
git config --global user.email "malhitticrypto@gmail.com"
git config --global user.name "malhitticrypto"

mkdir -p /home/malhitticrypto/universal-or-strategy/logs

# Pull latest repo (best-effort)
cd /home/malhitticrypto/universal-or-strategy && git pull --ff-only origin main || true

echo '[WAVE2] Launching parallel Bob Shell agents...'
screen -dmS v12-EPIC-CCN-164 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-164: Extract ProcessOnStateChange (complexity 91 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-164.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-164.log"
echo '[WAVE2] Launched: EPIC-CCN-164 (ProcessOnStateChange, CYC 91)'
sleep 1
screen -dmS v12-EPIC-CCN-107 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-107: Extract ProcessIpcCommands (complexity 76 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-107.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-107.log"
echo '[WAVE2] Launched: EPIC-CCN-107 (ProcessIpcCommands, CYC 76)'
sleep 1
screen -dmS v12-EPIC-CCN-108 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-108: Extract ProcessOnExecutionUpdate (complexity 67 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-108.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-108.log"
echo '[WAVE2] Launched: EPIC-CCN-108 (ProcessOnExecutionUpdate, CYC 67)'
sleep 1
screen -dmS v12-EPIC-CCN-109 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-109: Extract HydrateFSMsFromWorkingOrders (complexity 45 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-109.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-109.log"
echo '[WAVE2] Launched: EPIC-CCN-109 (HydrateFSMsFromWorkingOrders, CYC 45)'
sleep 1
screen -dmS v12-EPIC-CCN-110 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-110: Extract HandleFlatPositionUpdate (complexity 37 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-110.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-110.log"
echo '[WAVE2] Launched: EPIC-CCN-110 (HandleFlatPositionUpdate, CYC 37)'
sleep 1
screen -dmS v12-EPIC-CCN-111 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-111: Extract AdoptFleetOrders (complexity 37 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-111.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-111.log"
echo '[WAVE2] Launched: EPIC-CCN-111 (AdoptFleetOrders, CYC 37)'
sleep 1
screen -dmS v12-EPIC-CCN-112 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-112: Extract ExtractTargetConfiguration (complexity 31 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-112.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-112.log"
echo '[WAVE2] Launched: EPIC-CCN-112 (ExtractTargetConfiguration, CYC 31)'
sleep 1
screen -dmS v12-EPIC-CCN-113 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-113: Extract SweepBrokerOrders (complexity 28 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-113.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-113.log"
echo '[WAVE2] Launched: EPIC-CCN-113 (SweepBrokerOrders, CYC 28)'
sleep 1
screen -dmS v12-EPIC-CCN-114 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-114: Extract FlattenSinglePosition (complexity 27 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-114.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-114.log"
echo '[WAVE2] Launched: EPIC-CCN-114 (FlattenSinglePosition, CYC 27)'
sleep 1
screen -dmS v12-EPIC-CCN-115 bash -l -c "cd /home/malhitticrypto/universal-or-strategy && bob --accept-license --max-coins 50 -p 'Run epic-intake for EPIC-CCN-115: Extract ExecuteRetestEntry (complexity 26 -> 8)' > /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-115.log 2>&1; echo DONE_EXIT=$? >> /home/malhitticrypto/universal-or-strategy/logs/EPIC-CCN-115.log"
echo '[WAVE2] Launched: EPIC-CCN-115 (ExecuteRetestEntry, CYC 26)'
sleep 1

sleep 2
echo '[WAVE2] All 10 agents launched.'
screen -ls || true

echo '[WAVE2] Done. Logs: /home/malhitticrypto/universal-or-strategy/logs'