#!/usr/bin/env python3
"""
Generate Phase 2 (Architecture Planning) scripts for all pending epics.

Uses Building Blocks method: Copy Phase 1 scripts, modify phase-specific content only.
"""

import json
import os
from pathlib import Path

# Load epic roadmap
with open('epic_roadmap.json', 'r') as f:
    roadmap = json.load(f)

# Get all pending epics
pending_epics = [e for e in roadmap if e.get('status') == 'pending']
print(f"Found {len(pending_epics)} pending epics")

# Load API keys from JSON files
api_keys = {}
api_dir = Path.home() / '.bob' / 'api-keys'
for i in range(1, 11):
    key_file = api_dir / f'bob-api-key-{i:02d}.json'
    if key_file.exists():
        with open(key_file, 'r') as f:
            data = json.load(f)
            api_keys[i] = data['apikey']  # Note: 'apikey' not 'key'

print(f"Loaded {len(api_keys)} API keys")

# Generate Phase 2 scripts
scripts_dir = Path('scripts/wave1')
scripts_dir.mkdir(parents=True, exist_ok=True)

for i, epic in enumerate(pending_epics, 1):
    epic_num = epic['epic_number'].replace('EPIC-', '')
    epic_id = epic_num.replace('CCN-', '').zfill(3)
    
    # Determine API key (rotate through 10 keys)
    api_index = ((i - 1) % 10) + 1
    api_key = api_keys.get(api_index, '')
    
    if not api_key:
        print(f"WARNING: No API key for index {api_index}, skipping EPIC-{epic_id}")
        continue
    
    # Generate script content (copy Phase 1 pattern, change phase-specific content)
    script_content = f'''#!/bin/bash
set -e

# Phase 2: Architecture Planning for EPIC-{epic_id}
# Generated by generate_phase2_all_epics.py

EPIC_ID="{epic_num}"
LOG_DIR="logs/phase2"
MESSAGE_FILE="/tmp/phase2_msg_{epic_id}.txt"

# Create log directory
mkdir -p "$LOG_DIR"

# Set API key (hardcoded from JSON)
export BOBSHELL_API_KEY='{api_key}'

# Create message file
cat > "$MESSAGE_FILE" << 'EOFMSG'
You are executing Phase 2 (Architecture Planning) for $EPIC_ID.

**Input**: Read `docs/brain/$EPIC_ID/00-scope.md` (created in Phase 1)

**Task**: Create detailed architecture plan with:
1. Method signatures for extracted functions
2. Call graph analysis
3. Jane Street compliance checks
4. Risk assessment

**Output**: Write `docs/brain/$EPIC_ID/02-architecture-plan.md`

**Manifest**: Update `docs/brain/$EPIC_ID/manifest.json` with phase="2", status="completed"

**Verification**: After writing files, verify they exist on disk:
- Run: `ls -lh docs/brain/$EPIC_ID/02-architecture-plan.md`
- Run: `cat docs/brain/$EPIC_ID/manifest.json | grep '"phase": "2"'`

**Bobcoin Reporting**: You MUST report both cost and remaining balance in this format:
Cost: X.XX | Balance: Y.YY

Do NOT proceed until files are verified on disk.
EOFMSG

# Execute Bob Shell with --yolo flag (MANDATORY for file persistence)
cd /home/malhitticrypto/universal-or-strategy
bob --yolo --chat-mode plan "$(cat $MESSAGE_FILE)"

# Cleanup
rm -f "$MESSAGE_FILE"

echo "Phase 2 complete for $EPIC_ID"
'''
    
    # Write script
    script_path = scripts_dir / f'_p2_{epic_id}.sh'
    with open(script_path, 'w', newline='\n') as f:
        f.write(script_content)
    
    # Make executable
    os.chmod(script_path, 0o755)
    
    print(f"Generated: {script_path.name} (API key {api_index})")

print(f"\nGenerated {len(pending_epics)} Phase 2 scripts")
print(f"Next: Upload to VM and launch with rolling pattern")

# Made with Bob
